job/urls.py
from django.urls import path
from .views import category_jobs, job_apply, job_details, jobs, add_job, like_btn

urlpatterns = [
    path('', jobs, name = "job_list"),
    path('<int:id>', job_details, name='job_details'),
    path('addJob', add_job, name='jobEditor'),
    path('<int:id>/like', like_btn, name='like'),
    path('<int:id>/apply', job_apply, name='application'),
    path('<int:id>', category_jobs, name='category_jobs'),
]

app_name = 'job'

project/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='register')),
    path('admin/', admin.site.urls),   
    path('jobs/', include('job.urls', namespace='jobs')),
    path('contact-us/', include('contact.urls', namespace='contact')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('home.urls', namespace="home")),
    path('blogs/', include('blog.urls', namespace='blogs')),
    

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.conf import settings
from taggit.managers import TaggableManager
#from .views import Company 
# Create your models here.
JOB_CHOICES = (
    ("Part Time","Part Time"),
    ("Full Time", "Full Time"),
)

# customize imges name on the file system.
def upload_job_image(instance, filename):
    extension = filename.split('.')[1]
    return 'jobs/imags/%s.%s'%(instance.title, extension)
    
        

class Job(models.Model):
    owner = models.ForeignKey(User, related_name="jobs", on_delete=models.CASCADE)
    title = models.CharField(max_length = 150)
    #description = models.TextField(max_length = 1000)
    description = RichTextField(blank=True, null=True)
    job_type = models.CharField(max_length = 150, choices=JOB_CHOICES)
    published_at = models.DateTimeField(auto_now=True)
    vacancy = models.IntegerField(default=1)
    salary = models.IntegerField(default=1)
    experience = models.IntegerField(default=1)
    image = models.ImageField(upload_to=upload_job_image)
    likers = models.ManyToManyField(User, related_name='liked_jobs', blank=True)
    category = models.ForeignKey('Category', related_name='jobs', on_delete=models.SET_NULL, null=True)
    objects = models.Manager()
    skills = TaggableManager()

    def __str__(self):
        """Unicode representation of MODELNAME."""
        return self.title


class Category(models.Model):
    """Model definition for MODELNAME."""

    name = models.CharField(max_length = 150)

    def __str__(self):
        """Unicode representation of MODELNAME."""
        return self.name

       





    
    

    
            
    
    

    

job/forms.py
from django import forms 
from .models import  Job

# class EmployeeForm(forms.ModelForm):

#     class Meta:
#        model = Employee
#        fields = ["name", "email", "website", "cv", "cover_letter"]

class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = "__all__"       
        exclude = ("owner",'likers', 'likes_num')
        

job/views.py
from accounts.models import Profile, Company
from django.http.response import JsonResponse
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from .models import Category, Job
from .forms import  JobForm
from django.urls import reverse 
from django.contrib.auth.decorators import login_required
from .filters import JobFilter
from accounts.forms import EmployeeForm, ProfileForm
from django.contrib import messages
from django.core.mail import EmailMessage
from django.conf import settings

# Create your views here.
def jobs(request):

    jobs_list = Job.objects.all()
    my_filter = JobFilter(data=request.GET, queryset=jobs_list)
    jobs_list = my_filter.qs

    paginator = Paginator(jobs_list, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        "jobs_list": page_obj,
        'my_filter': my_filter
    }
    return render(request, "job/job_list.html", context)

def job_details (request, id):

    job_details = Job.objects.get(id=id)
    if request.method == 'POST':
        return redirect(reverse('jobs:application', args=[id]))
    context = {
        "job_details": job_details,       
    }
    return render(request, "job/job_details.html", context)

@login_required
def job_apply(request, id):

    job = Job.objects.get(id=id)
    user = request.user
    profile = Profile.objects.get(user=user)
    personal_info = user.candidate
    
    profile_form = ProfileForm(instance=profile)
    personal_info_form = EmployeeForm(instance=personal_info)
    if request.method == "POST":
        profile_form = ProfileForm(request.POST, instance=profile)
        personal_info_form = EmployeeForm(request.POST, request.FILES, instance=personal_info)
        if profile_form.is_valid() and personal_info_form.is_valid():
            form2 = profile_form.save(commit=False)
            form2.save()
            form3 = personal_info_form.save(commit=False)
            form3.save()
            form3.jobs.add(job)
            personal_info_form.save_m2m()
            messages.success(request, 'Your application has been accepted !')
            subject = f'{user.username} applied for your {job.title} job '
            message = f"{personal_info.cover_letter}"
            cv = request.FILES.getlist('cv')
            mail = EmailMessage(subject, message, settings.EMAIL_HOST_USER, [job.owner.email])
            for f in cv:
                mail.attach(f.name, f.read(), f.content_type)
            mail.send()
            return redirect(reverse('jobs:job_list'))



    context = {
        "form2": profile_form,
        "form3": personal_info_form,
        'job': job
    }

    return render(request, 'job/job_application.html', context)


@login_required
def add_job(request):
    if request.method == "POST":
        form = JobForm(request.POST, request.FILES)
        if form.is_valid:
            myForm = form.save(commit=False)
            myForm.owner = request.user
            myForm.save()
            return redirect(reverse("jobs:job_list"))
    else:
        form = JobForm()     

    context = {
        "jobForm": form,
    }       
    
    return render(request, "job/add_job.html", context)

def category_jobs(request, id):
    category = Category.objects.get(id=id)
    jobs = category.jobs
    my_filter = JobFilter(data=request.GET, queryset=jobs)
    jobs_list = my_filter.qs

    paginator = Paginator(jobs_list, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        "jobs_list": page_obj,
        'my_filter': my_filter
    }
    return render(request, "job/job_list.html", context)

@login_required
def like_btn(request, id):
    
    job = Job.objects.get(id=id)

    if request.user not in job.likers.all():
        job.likers.add(request.user)
        return JsonResponse({
        'status': 'ok',
        "message": "like"
    })
    job.likers.remove(request.user)
    
    return JsonResponse({
        'status': 'ok',
        "message": "dislike"
    })
    

job/templates/job/add_job.html
{% extends 'base.html' %}
{% load bootstrap4 %}

    {% block body %}

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Add Job</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            
                           
                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Add A New Job</h4>
                        </div>
                        
                    <div class="apply_job_form white-bg">
                      
                                {# Display a form #}

                            <form method="post" class="form" enctype="multipart/form-data">
                                
                                {% csrf_token %}
                                {{ jobForm.media}}
                                {% bootstrap_form jobForm %}
                                {% buttons %}
                                    
                                    <button class="boxed-btn3 w-100" type="submit">Submit</button>
                                    
                                
                                {% endbuttons %}
                            
                            </form>
                    </div>
                </div>
               
            </div>
        </div>
    </div>
    {% endblock %}
    
  

job/templates/job/job_application.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}


{% block body %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>apply for {{job.title}} Job</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<div class="job_details_area" style="padding: 0px;">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="job_details_header">
                    <div class="single_jobs white-bg d-flex justify-content-between">
                        
                       
                    </div>
                </div>
                <div class="descript_wrap white-bg">
                    <div class="single_wrap">
                        <h4>Apply</h4>
                    </div>
                    
                <div class="apply_job_form white-bg">
                  
                            {# Display a form #}

                        <form method="post" class="form" enctype="multipart/form-data">
                            
                            {% csrf_token %}
                            
                            
                            <hr>
                            {% bootstrap_form form2 %}
                            <hr>
                            {{ form3.media}}
                            {% bootstrap_form form3 %}

                            {% buttons %}
                                
                                <button class="boxed-btn3 w-100" type="submit">Submit</button>
                                
                            
                            {% endbuttons %}
                        
                        </form>
                </div>
            </div>
           
        </div>
    </div>
</div>
{% endblock body %}
    

job/templates/job/job_details.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}


    {% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job_details.title}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb" style="padding: 0;">
                                    <img src= "{{job_details.image.url}}" alt="{{job_details.title}}" style="object-fit: contain; max-width: 100%; max-height: 100%;">
                                </div>
                                <div class="jobs_conetent">
                                    <a href="#"><h4>{{job_details.title}}</h4></a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                        </div>
                                        <div class="location">
                                            <p> <i class="fa fa-clock-o"></i> {{job_details.job_type}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    
                                      
                                      {% if request.user in job_details.likers.all %}
                                        <a class="heart_mark"  onclick="likeIt(this)" data-set= '{{job_details.id}}'> <i id="heart{{job_details.id}}" class="fa fa-heart"></i> </a>
                                        <span id="counter{{job_details.id}}" > {{job_details.likers.count}} </span>
                                      {% else %}
                                        <a class="heart_mark"  onclick="likeIt(this)" data-set= '{{job_details.id}}'> <i id="heart{{job_details.id}}" class="ti-heart"></i> </a>
                                        <span id="counter{{job_details.id}}"> {{job_details.likers.count}} </span>
                                     {% endif %}
                                          
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Job description</h4>
                           <p>{{job_details.description|safe}}</p>
                        </div>
                        
                    </div>
                    <div class="apply_job_form white-bg">
                        <h4>Apply for the job</h4>
                      
                               

                            <form method="post" class="form" enctype="multipart/form-data">
                                <div class="row">
                                    {% csrf_token %}
                                <div class="col-md-12">
                                    <div class="submit_btn">
                                        <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                                    </div>
                                </div>
                            </div> 
                            </div>
                            </form>
                </div>
                <div class="col-lg-4 summery" >
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Job Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Published on: <span>{{job_details.published_at|date:'d M o' }}</span></li>
                                <li>Vacancy: <span>{{job_details.vacancy}} Position</span></li>
                                <li>Salary: <span>{{job_details.salary}}</span></li>
                                <li>Location: <span>California, USA</span></li>
                                <li>Job Nature: <span> {{job_details.job_type}}</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="share_wrap d-flex">
                        <span>Share at:</span>
                        <ul>
                            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                        </ul>
                    </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    {% endblock %}
    
  

job/templates/job/job_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
    {% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <div class="alert alert-success" role="alert">
                        {{ message }}
                    </div>
                    
                    {% endfor %}
                </ul>
            {% endif %}
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{ jobs_list.paginator.count }}+ Jobs Available</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form action="." method="GET">
                                {% bootstrap_form my_filter.form %}

                                    <input type="submit" class="boxed-btn3 w-100" value="Search">                                                                     
                            </form>
                        </div>
                   
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <h4>Job Listing</h4>
                                </div>
                                <div class="col-md-6">
                                    <div class="serch_cat d-flex justify-content-end">
                                        <select>
                                            <option data-display="Most Recent">Most Recent</option>
                                            <option value="1">Marketer</option>
                                            <option value="2">Wordpress </option>
                                            <option value="4">Designer</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        <div class="row">
                            {% for job in jobs_list %}
                            <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="thumb" style="padding: 0px;">
                                            <img src="{{job.image.url}}" alt="{{job.title}}" style="object-fit: contain; max-width: 100%; max-height: 100%;">
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{% url 'jobs:job_details' job.id %}"><h4>{{job.title}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                                </div>
                                                <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i> {{job.job_type}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">

                                            {% if request.user in job.likers.all %}
                                                <a class="heart_mark"  style="margin-right: 0px;" onclick="likeIt(this)" data-set= '{{job.id}}'> <i id="heart{{job.id}}" class="fa fa-heart"></i> </a>
                                                <span id="counter{{job.id}}" data-id="{{job.id}}" style="margin-right: 10px;"> {{job.likers.count}} </span>
                                            {% else %}
                                                <a class="heart_mark" style="margin-right: 0px;" onclick="likeIt(this)" data-set= '{{job.id}}'> <i id="heart{{job.id}}" class="ti-heart"></i> </a>
                                                <span id="counter{{job.id}}" data-id="{{job.id}}" style="margin-right: 10px;" > {{job.likers.count}} </span>
                                            {% endif %}

                                            <!-- <a class="heart_mark" href="#" style="margin-right: 0px;"> <i class="fa fa-heart" ></i> </a>
                                            <span id="counter" style="margin-right: 10px;"> {{job.likers.count}} </span> -->

                                            <a href="{% url 'jobs:job_details' job.id %}" class="boxed-btn3">Apply Now</a>
                                        </div>
                                        <div class="date">
                                            <p>{{job.published_at|date:'d M o' }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                            
                        </div>
                        <div class="row">
                            {% if jobs_list.has_other_pages %}
                            
                            <div class="col-lg-12">
                                <div class="pagination_wrap">
                                    <ul>
                                        {% if jobs_list.has_previous %}
                                        <li><a href="?page={{jobs_list.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                        {% endif %}   
                                        {% for i in jobs_list.paginator.page_range %}
                                        <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                        {% endfor %}  
                                        {% if jobs_list.has_next %}
                                            <li><a href="?page={{jobs_list.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                        {% endif %}  
                                    </ul>
                                </div>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock body %}