accounts/urls.py
from django.urls import path
from .views import profile, edit_profile, sign_up_candidate, sign_up_company

urlpatterns = [
    path('signup/candidate',sign_up_candidate , name = "sign_up_candidate"),
    path('signup/company',sign_up_company , name = "sign_up_company"),
    path('profile/',profile , name = "profile"),
    path('profile/edit', edit_profile, name = "profile_editor"),
] 

app_name = 'accounts'

job/urls.py
from django.urls import path
from .views import category_jobs, job_apply, job_details, jobs, add_job, like_btn

urlpatterns = [
    path('', jobs, name = "job_list"),
    path('<int:id>', job_details, name='job_details'),
    path('addJob', add_job, name='jobEditor'),
    path('<int:id>/like', like_btn, name='like'),
    path('<int:id>/apply', job_apply, name='application'),
    path('<int:id>', category_jobs, name='category_jobs'),
]

app_name = 'job'

project/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='register')),
    path('admin/', admin.site.urls),   
    path('jobs/', include('job.urls', namespace='jobs')),
    path('contact-us/', include('contact.urls', namespace='contact')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('home.urls', namespace="home")),
    path('blogs/', include('blog.urls', namespace='blogs')),
    

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from ckeditor.fields import RichTextField
from django.conf import settings
from taggit.managers import TaggableManager
from job.models import Category, Job 


# Create your models here.
def upload_company_image(instance, filename):
    extension = filename.split('.')[1]
    return 'companies/logos/%s.%s'%(instance.id, extension)
   
def upload_cv(instance, filename):
    extension = filename.split('.')[1]
    return 'candidaties/cvs/%s.%s'%(instance.id, extension)

def upload_image(instance, filename):
    extension = filename.split('.')[1]
    return 'candidaties/images/%s.%s'%(instance.id, extension)


class Profile(models.Model):
    user =  models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    phone = models.CharField(max_length = 15)
    city = models.ForeignKey("City", on_delete=models.CASCADE, null=True, related_name='user_profile')
    

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)    

class City(models.Model):
    name = models.CharField(max_length = 50) 

    def __str__(self):
        return self.name
    
class Company(models.Model):
    logo = models.ImageField(upload_to=upload_company_image, null=True, blank=True)
    employee_num = models.IntegerField(default=0)
    description = RichTextField(blank=True, null=True)
    user =  models.OneToOneField(User, on_delete=models.CASCADE, related_name='company')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    
    def __str__(self):
        """Unicode representation of MODELNAME."""
        return self.user.first_name

class Employee(models.Model):
    job_title = models.CharField(max_length = 13)
    bio = models.TextField(max_length=500)
    user =  models.OneToOneField(User, on_delete=models.CASCADE, related_name='candidate')
    image = models.ImageField(upload_to=upload_image, null=True, blank=True)
    website = models.URLField(max_length = 300)
    cv = models.FileField(upload_to=upload_cv, null=True, blank=True)
    summary = RichTextField(blank=True, null=True)
    jobs = models.ManyToManyField(Job, related_name='candidaties', blank=True)
    objects = models.Manager()
    skills = TaggableManager()
    def __str__(self):
        return self.user.username
    
    

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Profile, Company, Employee 

class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email','first_name', 'last_name', 'password1', 'password2']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['city', 'phone']

class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['logo', 'employee_num', 'description', 'category']

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'
        exclude = ['user', 'jobs']
        

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

class UserForm2(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

accounts/views.py
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from .forms import SignUpForm, ProfileForm, UserForm, CompanyForm, EmployeeForm
from django.contrib.auth import authenticate, login
from .models import Company, Profile
from django.contrib import messages
from django.urls import reverse


# Create your views here.
def sign_up_candidate(request):
    

    if request.method == "POST":
        form1 = SignUpForm(request.POST)
        form2 = EmployeeForm(request.POST, request.FILES)    
        if form1.is_valid() and form2.is_valid():
            print('valid')
            form1.save()
            username = form1.cleaned_data.get('username')
            password = form1.cleaned_data.get('password1')
            
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                candidate_form = form2.save(commit=False)
                candidate_form.user = request.user
                candidate_form.save()
                form2.save_m2m()
                messages.success(request, 'Your have been successfully registered !')
                return redirect(reverse("register:profile"))

            else: 
                
                return HttpResponse('there something wrong !')
    else:
        form1 = SignUpForm()
        form2 = EmployeeForm()

    context = {
        'form1': form1,
        "form2":form2
    }

    return render(request, 'registration/signup.html', context)

def sign_up_company(request):
    
    if request.method == "POST":
        
        form1 = SignUpForm(request.POST)
        form2 = CompanyForm(request.POST, request.FILES)    
        if form1.is_valid() and form2.is_valid():
            form1.save()
            username = form1.cleaned_data.get('username')
            password = form1.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            if user:
                    login(request, user)
                    company_form = form2.save(commit=False)
                    company_form.user = user
                    company_form.save()
                    messages.success(request, 'Your have been successfully registered !')
                    return redirect(reverse("register:profile"))

            else: 
                    
                    return HttpResponse('there something wrong !')
    else:
        form1 = SignUpForm()
        form2 = CompanyForm()

    context = {
        'form1': form1,
        "form2": form2
    }

    return render(request, 'registration/signup.html', context)

def profile(request):

    profile = Profile.objects.get(user=request.user)
    return render(request, 'accounts/profile.html', {'profile': profile})

def edit_profile(request):
    
    profile = Profile.objects.get(user=request.user)
    if request.method == "POST":
        profileform = ProfileForm(request.POST,request.FILES, instance=profile)
        userform = UserForm(request.POST, instance=request.user )
        if profileform.is_valid() and userform.is_valid():
            userform.save()
            my_profileform = profileform.save(commit=False) 
            my_profileform.user = request.user
            my_profileform.save()
            return redirect('/accounts/profile')
    else:
        profileform = ProfileForm(instance=profile)
        userform = UserForm(instance=request.user)

    context = {
        'profileform': profileform,
        'userform': userform,
    }
    return render(request, 'accounts/profile_edit.html', context)

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->
    {% block body %}
    <!-- header-start -->

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <div class="alert alert-success" role="alert">
                        {{ message }}
                    </div>
                    
                    {% endfor %}
                </ul>
            {% endif %}
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job_details.title}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                
                <div class="col-lg-8 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                          
                            <h3>Profile Summery</h3>
                        </div> 
                        <div class="job_content">
                            <ul>
                                <li>Name: <span>{{profile.user.username}}</span></li>
                                <li>Phone: <span>{{profile.phone}}</span></li>
                                <li>Email: <span>{{profile.user.email}}</span></li>
                                <li>Location: <span>{{profile.city.name}}</span></li>
                                
                            </ul>
                        </div>
                        <div class="p-6">
                            <a class="boxed-btn3 w-100" href="{% url 'register:profile_editor' %}">Edit Profile</a>
                        </div>
                    </div>
                    
            
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
    <!-- footer start -->
  
</body>

</html>

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}
<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->
    
    <!-- header-start -->
    {% block body %}
    <!-- header-end -->

   
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            
                           
                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Edit Profile</h4>
                        </div>
                        
                    <div class="apply_job_form white-bg">
                      
                                {# Display a form #}

                            <form method="post" class="form" enctype="multipart/form-data">
                                
                                {% csrf_token %}
                                {% bootstrap_form userform %}
                                {% bootstrap_form profileform %}
                                
                                {% buttons %}
                                    
                                        <button class="boxed-btn3 w-100" type="submit">Submit</button>
                                    
                                
                                {% endbuttons %}
                            </div> 
                            </form>
                    </div>
                </div>
               
            </div>
        </div>
    </div>
    {% endblock %}
    <!-- footer start -->
  
</body>

</html>